version: '3'

services:
  lab:
    image: jupyter/datascience-notebook
    ports:
      - "8888:8888"    
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      JUPYTER_TOKEN: verduritas